name: complex
on: push
jobs:
    job1:
        name: Date Job1
        runs-on: ubuntu-latest
        steps:
            - run:  echo "date"
    job2:
        name: Date Job2
        runs-on: windows-latest
        steps:
            - run:  echo "date"
    job3:
        name: Date Job3
        runs-on: macos-latest
        steps:
            - run:  echo "date"
    job4:
        needs: [job1, job2, job3]
        name: Date Job4
        runs-on: windows-latest
        steps:
            - run:  echo "date"
