name: complex
on: push
jobs:
    job1:
        name: Date Job1
        runs-on: ubuntu-latest
        steps:
            - name: step date
              uses: Tiwalade18/checkout@v2
            - name: step date two
              run:  echo "Today is " . date("Y/m/d") . "<br>"
    job2:
        name: Date Job2
        runs-on: windows-latest
        steps:
            - name: step date
              uses: Tiwalade18/checkout@v2
            - name: step date two
              run:  echo "Today is " . date("Y/m/d") . "<br>"
    job3:
        name: Date Job3
        runs-on: macos-latest
        steps:
            - name: step date
              uses: Tiwalade18/checkout@v2
            - name: step date two
              run:  echo "Today is " . date("Y/m/d") . "<br>"
    job4:
        needs: [job1, job2, job3]
        name: Date Job4
        runs-on: windows-latest
        steps:
            - name: step date
              uses: Tiwalade18/checkout@v2
            - name: step date two
              run:  echo "Today is " . date("Y/m/d") . "<br>"
